apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: azac90wt1-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1fafa28002.hdtj.p3.openshiftapps.com/rhtap/rhtap-qe:2fcf54cdba7c41a04f8a5f4643940309865d671b@sha256:1c479ffadf9743a4dabd96c76857682e10567c6b329ae0be37d1745eb5675ff0
          name: container-image
